{:title "About"
 :layout :page
 :page-index 0
 :navbar? true}

== Personal Details
[horizontal]

Name:: Mark Janssen
Role:: Solutions Architect
Location:: Arnhem, The Netherlands
Email:: mpc.janssen@gmail.com
Web:: 
* Personal: https://mpcjanssen.nl
* Github: https://github.com/mpcjanssen
* LinkedIn: https://www.linkedin.com/pub/mark-janssen/1/2a7/44
* Tclers Wiki: http://wiki.tcl.tk/MJ


== Summary
Mark is a motivated Information Architect with a wide experience in different ICT areas. He has managed sizeable LEAN improvement projects in which he advised the customer management on improvement of the processes. The improvements he proposed and implemented have resulted in an improved operational efficiency between 15 and 25%.

Because of his broad experience and analytical quality, Mark is able to quickly understand new processes and identify the bottlenecks in these processes. Mark's open way of communicating and his affinity with both technical and commercial aspects leads to improvements with buy in from both internal and external customers. His pragmatic and realistic mindset allows him to implement the improvements within budget and on time. His enthusiasm allows him to introduce others in a continuous improvement and LEAN mindset.

From a technical background as software developer and tester, Mark has grown as an experienced solution integrator and architect with experience in Banking, Telecom, ICT service delivery. His interest in process improvement has allowed him to develop into a LEAN project manager in an international setting with projects in the Netherlands, France, the UK, India and South East Asia.

Mark likes to be an intermediary between customer and supplier and business and IT. Here his analytical ability and communication skills shine. Within LEAN management, Mark can use and improve both skills.

== Experience

* Developer of Simpletask
* Solution Architecture
* Operational excellence and LEAN management
* Operating in an international environment with offshored development centers
* System integration with a focus on Telecom
* Application maintenance with a focus on Telecom
* Application development, mainly in C, Tcl and Java.
* Software testing

Languages
Dutch: Fluent
English: Fluent
German: Basic
Education
TOGAF 9.1 Level 2 Certified
BiSL Foundation
ITILv2 Foundation
PRINCE2 Foundation
Bachelor of Science in Physics
Detailed experience
Developer, Simpletask, 2013 - Present

Because existing task management applications on Android didn't fulfil my requirements I decided to create my own application based on the existing Todottxt application. The resulting application Simpletask has been downloaded over 10.000 times from the Google Play Store and over 30.000 times from FDroid. My effort to stay engaged with the user base and fix issues as soon as possible has resulted in excellent user reviews.

Process Manager, KPN Telecom, November 2011 - Present

Part of the process management team of KPN Mobile.
Ensure innovations projects on the mobile network are implemented in a controlled manner and according to ITIL processes.
Assess changes in the mobile network as chairman of the Change Acceptance Board.
Propose and implement process improvements.
Redesigned incident process for Telfort Value Added Services after integration in the KPN network.
Coach collegues in process management subjects suchs as A3 reporting and Value Chain analysis.
Represent maintenance interests in discussions with internal and external 3rd parties.
Senior Lean Consultant, Atos Origin, July 2011 - November 2011

Because of the actual market circumstances the utilisation of the Atos Technology colleagues was waning. In order to improve utilisation, I have used Lean techniques to optimize the way of working of the internal resourcing office. During this period I have performed the following tasks:

Coaching of the resource managers in application of Lean techniques.
Analysis of the current processes using Value Stream Mapping and SIPOCs (Supplier, Input, Process, Output, Customer)
Keep Atos Technology Services updated about project status and results.
Define the improvement actions to counter issues found during analysis.
Guide the implementation of the improvement actions while emphasizing continuous improvement and coaching.
Lean Consultant, Atos Origin, June 2010 - June 2011

Lean Consultant, Atos Origin, December 2009 - June 2010

Solution Architect, Atos Origin, December 2008 - November 2009

Java Developer, ING (for Atos Origin), April 2008 - November 2008

Wrote the migration functionality for former Postbank credit cards to ING Card. Functionallity was written in Java using Hibernate and Spring.
Improved Continuous Integration setup to reduce the unit testing time from 5 minutes to 30 seconds greatly improving the ability to do Test Driven Development.
Java Developer, Atos Origin, April 2008 - November 2008

Developer, NXP Semiconductors (for LogicaCMG), March 2007 - March 2008

Developed scripts in the shopfloor control software to automate wafer measurement machines.
Developed a SECS machine emulator in Tcl to test automation scripts without having to stop actual factory equipment.
Architect, Air Traffic Control NL (for LogicaCMG), January 2007 - March 2007

Wrote the Subsystem Design for the new radar scopes used by the Dutch Air Traffic controllers.
Software Tester, NXP Semiconductors (for LogicaCMG), November 2006 - January 2007

Implementation Engineer, Province South Holland (for LogicaCMG), October 2006 - November 2006

Solutions Integrator, T-Mobile International (for LogicaCMG), September 2005 - October 2006

Developer, LogicaCMG, July 2005 - September 2006

Solutions Integrator, T-Mobile International (for LogicaCMG), July 2004 - June 2005

Implementation Engineer, LogicaCMG, January 2004 - June 2004

Implementation Engineer, LogicaCMG, March 2003 - December 2003

Implementation Engineer, LogicaCMG, July 2002 - February 2003

C Developer, CMG Wireless Networks, January 2002 -June 2002

C Developer, CMG Wireless Networks, July 2001 - December 2001

Tester, Rabofacet (for CMG), September 1998 - October 1999

